#!/usr/bin/env bash

println() {
    printf "%s\n" "$1" 
}

progress_bar() {
    i=$1
    while [ "$i" -le "$2" ];
    do

    sleep .1
    printf "."
    echo $((i+=1)) >/dev/null

    done
    println
}

BEGIN=true
END=false
while getopts "eh?" option
do
    case "${option}"
        in
        e)
            BEGIN=false
            END=true
            ;;
        h)
            println "Use flag -e (end) to end development, default behavior starts development."
            ;;
        *)
            println "Use flag -e (end) to end development, default behavior starts development."
            ;;
    esac
done

if [ $BEGIN == true ]
then
    println "Beginning Development, Starting Hugo Server"
    hugo server -w -D -F --disableFastRender >> /dev/null &
    progress_bar 0 25
    println "Hugo Server Started"
    println "http://localhost:1313"
    println "Starting Firefox..."
    firefox --private-window localhost:1313  >> /dev/null 2>&1 &
elif [ $END == true ]
then
    println "Stopping Hugo Server..."
    killall hugo >> /dev/null
    println "Hugo Server Stopped!"
fi
